name: Updater

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  updater:
    name: update-checker
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Run Updater
      id: update
      run: node .github/updater/index.js
      continue-on-error: true
      
    - name: Commit and Push Changes
      if: steps.update.outcome == 'success'
      run: |
        git checkout -b "${{ steps.update.outputs.latestVersion }}"
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git commit -am "${{ steps.update.outputs.latestVersion }}"
        git push -u origin "${{ steps.update.outputs.latestVersion }}"

    - name: Create Pull Request
      if: steps.update.outcome == 'success'
      run: |
        gh pr create \
          --title "${{ steps.update.outputs.latestVersion }}" \
          --body "Automatically generated by a GitHub action." \
          --head "${{ steps.update.outputs.latestVersion }}" \
          --base master
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN }}